### ISSUE TITLE
Ricardo, could you please add 'cc' 

### ISSUE THREAD

**Issue by CreswellCasey** [yanezricardo/MailerSendNetCore#3]
Hi Ricardo
Great code for Mailersend.
Can I suggest to please also add 'cc' in addition to the 'bcc' that you've already coded for.

Thanks
Cres

**Comment by yanezricardo** [comment]
Hi CreswellCasey, yes of course, I will do it ASAP!

**Comment by CreswellCasey** [comment]
Super awesome Ricardo!
